OBJECTS_FILTER = set([
    'person',
    'horse',
    'dog',
    'cow',
    'cat',
    'bird',
    'sheep'
])

MAP_PART_TO_CLASS = {
    # 'head': 'head', 
    # 'hair': 'head',
    #  
    'torso': 'body', 
    
    'llarm': 'leg', 
    'luarm': 'leg', 
    'llleg': 'leg', 
    'luleg': 'leg', 
    'lfoot': 'leg', 
    'rlleg': 'leg', 
    'ruleg': 'leg', 
    'rfoot': 'leg', 
    'lhand': 'leg', 
    'rlarm': 'leg', 
    'rhand': 'leg', 
    'ruarm': 'leg', # LOLOL
    # 'fwheel': 16, 
    # 'bwheel': 17, 
    # 'handlebar': 18, 
    # 'chainwheel': 19,

    'saddle': 'body', 

    # 'beak': 'head', 

    'rleg': 'leg', 

    'tail': 'tail', 
    
    # 'frontside': 24,
    # 'rightside': 25, 
    # 'window_1': 26, 
    # 'headlight_1': 27, 
    # 'wheel_1': 28, 
    # 'fliplate': 29, 
    # 'rightmirror': 30, 
    # 'headlight_2': 31, 
    # 'wheel_2': 32, 
    # 'window_2': 33, 

    # 'lear': 'head', 
    # 'rear': 'head', 
    # 'leye': 'head', 
    # 'reye': 'head', 
    # 'lebrow': 'head', 
    # 'rebrow': 'head', 
    # 'mouth': 'head', 
    # 'nose': 'head', 
    # 'neck': 'head', 

    # 'pot': 43, 
    # 'plant': 44, 
    # 'leftside': 45, 
    # 'body': 46, 
    # 'cap': 47, 
    # 'door_1': 48, 

    # 'lwing': 'wing', 
    # 'rwing': 'wing', 

    # 'muzzle': 'head', 

    'lfleg': 'leg', 
    'lfpa': 'leg', 
    'rfleg': 'leg',
    'rfpa': 'leg', 
    'rbleg': 'leg', 
    'rbpa': 'leg', 
    'lbleg': 'leg', 
    'lbpa': 'leg', 
    'lleg': 'leg', 
    # 'screen': 61, 
    # 'leftmirror': 62, 
    # 'window_3': 63, 
    # 'coach_1': 64, 
    # 'coach_2': 65, 
    'lflleg': 'leg', 
    'lfuleg': 'leg', 
    'lfho': 'leg', 
    'rflleg': 'leg', 
    'rfho': 'leg', 
    'lblleg': 'leg', 
    'lbuleg': 'leg', 
    'lbho': 'leg', 
    # 'stern': 74, 
    # 'engine_1': 75, 
    # 'coach_3': 76, 
    # 'coach_4': 77, 
    # 'cleftside_1': 78, 
    # 'cleftside_2': 79, 
    # 'cleftside_3': 80, 
    # 'cleftside_4': 81, 
    # 'hfrontside': 82, 
    # 'hleftside': 83, 
    # 'cfrontside_1': 84, 
    'rfuleg': 'leg',
    'rbuleg': 'leg', 
    # 'crightside_1': 87, 
    # 'hrightside': 88, 
    # 'hroofside': 89, 
    # 'backside': 90, 
    # 'wheel_3': 91, 
    # 'window_4': 92, 
    # 'window_5': 93, 
    # 'window_6': 94, 
    # 'bliplate': 95, 
    # 'crightside_2': 96, 
    # 'crightside_3': 97, 
    # 'croofside_1': 98, 
    # 'croofside_2': 99, 
    # 'croofside_3': 100,
    #  
    # 'lhorn': 'head', 
    # 'rhorn': 'head', 

    # 'roofside': 103, 

    'rblleg': 'leg'

    # 'headlight_3': 105, 
    # 'window_7': 106, 
    # 'window_8': 107, 
    # 'window_9': 108, 
    # 'rbho': 109, 
    # 'door_2': 110, 
    # 'door_3': 111, 
    # 'headlight_4': 112, 
    # 'headlight_5': 113, 
    # 'headlight_6': 114, 
    # 'hbackside': 115, 
    # 'engine_2': 116, 
    # 'window_10': 117, 
    # 'wheel_4': 118, 
    # 'wheel_5': 119, 
    # 'wheel_6': 120, 
    # 'coach_5': 121, 
    # 'coach_6': 122, 
    # 'cleftside_5': 123, 
    # 'cleftside_6': 124, 
    # 'cbackside_1': 125, 
    # 'cfrontside_2': 126, 
    # 'wheel_7': 127, 
    # 'wheel_8': 128, 
    # 'engine_3': 129, 
    # 'engine_4': 130, 
    # 'coach_7': 131, 
    # 'coach_8': 132, 
    # 'coach_9': 133, 
    # 'cleftside_7': 134, 
    # 'cleftside_8': 135, 
    # 'cleftside_9': 136, 
    # 'cfrontside_3': 137, 
    # 'cfrontside_4': 138, 
    # 'cfrontside_5': 139, 
    # 'cfrontside_6': 140, 
    # 'cfrontside_7': 141, 
    # 'cfrontside_9': 142, 
    # 'cbackside_2': 143, 
    # 'headlight_7': 144, 
    # 'window_11': 145, 
    # 'window_12': 146, 
    # 'window_13': 147, 
    # 'window_14': 148, 
    # 'window_15': 149, 
    # 'window_16': 150, 
    # 'window_17': 151, 
    # 'window_18': 152, 
    # 'window_19': 153, 
    # 'window_20': 154, 
    # 'crightside_4': 155, 
    # 'crightside_5': 156, 
    # 'croofside_4': 157, 
    # 'headlight_8': 158, 
    # 'crightside_6': 159, 
    # 'crightside_7': 160, 
    # 'croofside_5': 161, 
    # 'engine_5': 162, 
    # 'engine_6': 163, 
    # 'door_4': 164, 
    # 'crightside_8': 165
}